import Head from "next/head";
import Navbar from "../components/Navbar";
import Ribbon from "../components/Ribbon";
import Image from "next/image";
import slugging from "../public/Rick_Slugging.jpg";
import seats from "../public/Rick_seats.jpg";

import styles from "../styles/Home.module.css";
import style from "../styles/Schedule.module.css";

export default function Schedule() {
  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>About us | Bills on Tap!</title>
          <meta name="description" content="Generated by Garrity Inc." />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.ribbonRow}>
          <Ribbon />

          <main>
            <div>
              <h1>About us</h1>
              <div>
                Just 2 diehard Bills fans giving their unsolicited and
                uncensored opinion of the Buffalo Bills.
              </div>
              <h2>View from our Game Day perspective</h2>
              <div>
                <Image src={seats} alt="Picture of our seats" />
              </div>
              <div>
                <Image
                  src={slugging}
                  alt="Picture of the Ricky Slugging a beer"
                />
              </div>
            </div>
          </main>
          <Ribbon />
        </div>

        <footer className={styles.footer}>
          <a href="http://www.espn.com">Powered by Deeds Media Inc.</a>
        </footer>
      </div>
    </>
  );
}
