import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bills on Tap!</title>
        <meta name="description" content="Generated by Garrity Inc." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Bills on Tap!</h1>
        <div>
          <iframe
            src="https://open.spotify.com/embed/show/0mjPuqXiycfAilmzOOsowP"
            width="100%"
            height="232"
            frameBorder="0"
            allowtransparency="true"
            allow="encrypted-media"
          ></iframe>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="http://www.espn.com">Powered by Deeds</a>
      </footer>
    </div>
  );
}
