import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bills on Tap!</title>
        <meta name="description" content="Generated by Garrity Inc." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Bills on Tap!</h1>
      </main>

      <footer className={styles.footer}>
        Powered by <a href="http://www.espn.com">Deeds</a>
      </footer>
    </div>
  );
}
