import Head from "next/head";
import Navbar from "../components/Navbar";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Podcasts() {
  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <Head>
          <title>Bills on Tap!</title>
          <meta name="description" content="Generated by Garrity Inc." />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Listen Up -- Bills on Tap!</h1>
          <div className={styles.episode}>
            <h3>Episode 2</h3>
            <div>
              <iframe
                src="https://open.spotify.com/embed/show/0mjPuqXiycfAilmzOOsowP"
                width="100%"
                height="232"
                frameBorder="0"
                allowtransparency="true"
                allow="encrypted-media"
              ></iframe>
            </div>
          </div>
          <div className={styles.episode}>
            <h3>Episode 1</h3>
            <div>
              <iframe
                src="https://open.spotify.com/embed/episode/1kLxp5ts60J3F5ynmf4RBx"
                width="100%"
                height="232"
                frameBorder="0"
                allowtransparency="true"
                allow="encrypted-media"
              ></iframe>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
